apiVersion: scaffolder.backstage.io/v1beta3
kind: Template

metadata:
  name: retrofit-jenkins-argocd
  title: Integrate CI/CD into Developer's Existing Repository
  description: Run your CI and CD using Developer's own Repo

spec:
  owner: development
  type: service

  parameters:
    - title: Select Existing Repository
      required:
        - repoUrl
        - component_id
        - environment

      properties:

        repoUrl:
          title: Repository URL
          type: string
          pattern: ^https://github.com/Backstage-IDP-PoC/[a-zA-Z0-9._-]+$
          description: |
            Enter GitHub repo URL from Backstage-IDP-PoC org only.
            Example:
            https://github.com/Backstage-IDP-PoC/my-app

        component_id:
          title: Component Name
          type: string

        environment:
          title: Environment
          type: string
          enum:
            - dev
            - uat
            - staging
            - prod

steps:

  # ✅ 1. Fetch CI/CD template files
  - id: fetch-base
    name: Fetch CI/CD Templates
    action: fetch:template
    input:
      url: ./template
      values:
        app_name: ${{ parameters.component_id }}
        app_env: ${{ parameters.environment }}

  # ✅ 2. CLONE EXISTING REPO
  - id: clone
    name: Clone existing repo
    action: github:repo:clone
    input:
      repoUrl: github.com?owner=Backstage-IDP-PoC&repo=${{ parameters.component_id }}

  # ✅ 3. MERGE FILES INTO EXISTING REPO
  - id: merge
    name: Merge CI/CD into repo
    action: fs:copy
    input:
      sourcePath: ./        # template files
      targetPath: ${{ steps.clone.output.repoDir }}

  # ✅ 4. COMMIT & PUSH
  - id: push
    name: Commit and push changes
    action: github:repo:push
    input:
      repoUrl: github.com?owner=Backstage-IDP-PoC&repo=${{ parameters.component_id }}
      sourcePath: ${{ steps.clone.output.repoDir }}

