apiVersion: scaffolder.backstage.io/v1beta3
kind: Template

metadata:
  name: retrofit-jenkins-argocd
  title: Integrate CI/CD into Developer's Existing Repository
  description: Run your CI and CD using Developer's own Repo

spec:
  owner: development
  type: service

  parameters:
    - title: Select Existing Repository
      required:
        - repoUrl
        - component_id
        - environment

      properties:

        repoUrl:
          title: Repository URL
          type: string
          pattern: ^https://github.com/Backstage-IDP-PoC/[a-zA-Z0-9._-]+$
          description: |
            Enter GitHub repo URL from Backstage-IDP-PoC org only.
            Example:
            https://github.com/Backstage-IDP-PoC/my-app

        component_id:
          title: Component Name
          type: string

        environment:
          title: Environment
          type: string
          enum:
            - dev
            - uat
            - staging
            - prod

  steps:

    # ✅ 1. Fetch Template Files
    - id: fetch-base
      name: Fetch Template Files
      action: fetch:template
      input:
        url: ./template
        values:
          app_name: ${{ parameters.component_id }}
          app_env: ${{ parameters.environment }}

    # ✅ 2. DIRECT PUSH (NO PR)
    - id: push-to-repo
      name: Push CI/CD directly to repo
      action: publish:github
      input:
        repoUrl: ${{ parameters.repoUrl | parseRepoUrl }}
        defaultBranch: main
        sourcePath: ./

    # ✅ 3. Create GitOps Manifests
    - id: push-k8s-manifest
      name: Push Kubernetes manifests
      action: publish:github
      input:
        repoUrl: github.com?owner=Backstage-IDP-PoC&repo=k8s-manifest
        defaultBranch: main
        sourcePath: ./manifest-templates

  output:
    links:
      - title: 🔧 Open Repository
        url: ${{ parameters.repoUrl }}

      - title: 🚀 Trigger Jenkins Build
        url: http://35.208.92.122:8080/job/${{ parameters.component_id }}/build

      - title: 📦 Open ArgoCD App
        url: https://35.184.124.65/applications/${{ parameters.component_id }}
